sudo: required
services:
  - docker

before_install:
  - docker build -t gokuljayaraj/mt-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gokuljayaraj/mt-client npm run test

after_success:
  - docker build -t gokuljayaraj/mt-client ./client
  - docker build -t gokuljayaraj/mt-server ./server
  - docker build -t gokuljayaraj/mt-worker ./worker
  - docker build -t gokuljayaraj/mt-nginx ./nginx

