sudo: required
services:
  - docker

before_install:
  - docker build -t gokuljayaraj/mt-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gokuljayaraj/mt-client npm run test

after_success:
  - docker build -t gokuljayaraj/mt-client ./client
  - docker build -t gokuljayaraj/mt-server ./server
  - docker build -t gokuljayaraj/mt-worker ./worker
  - docker build -t gokuljayaraj/mt-nginx ./nginx
  - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push gokuljayaraj/mt-client
  - docker push gokuljayaraj/mt-server
  - docker push gokuljayaraj/mt-worker
  - docker push gokuljayaraj/mt-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "mt-web-app"
  env: "Mt-web-app-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-781829211718"
  bucket_path: "mt-web-app"
  on:
    branch: main
  access_key_id: "$AWS_AK"
  secret_access_key: "$AWS_SK"